---
- hosts: localhost
  tasks:
    - name: Pull Docker image from Docker Hub
      shell: docker pull prajit1999/calculator:latest

    - name: Run Docker container
      shell: docker run -d -p 8081:8080 prajit1999/calculator:latest
